[tools]
nodejs=["18", "19"]
python = "3.12.0"
pnpm='7.30.0'
poetry = "1.4.0"
pdm = "latest"
java = "20.0.2"
pipx="latest"
rye="latest"
go = "latest"

[plugins]
# specify a custom repo url
# note this will only be used if the plugin does not already exist
python = 'https://github.com/jdxcode/rtx-python'
pnpm ='https://github.com/jonathanmorley/asdf-pnpm'
poetry='https://github.com/asdf-community/asdf-poetry'
# pdm='https://github.com/1oglop1/asdf-pdm'


[settings]
experimental = true
